---
version: '3'
services:

# START SERVICE filebeat.kafka
  filebeat:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.filebeat.kafka:7.8.0
    environment: ['ES_FILEBEAT_KAFKA_HOSTS=${INGEST_KAFKA_SASL_ENVIRONMENT_KAFKA_HOSTS}','ES_FILEBEAT_KAFKA_TOPICS=${INGEST_KAFKA_SASL_ENVIRONMENT_KAFKA_TOPICS}','ES_FILEBEAT_KAFKA_CONSUMERGROUP=${INGEST_KAFKA_SASL_ENVIRONMENT_KAFKA_CONSUMERGROUP}','ES_FILEBEAT_KAFKA_INITIAL_OFFSET=${INGEST_KAFKA_SASL_ENVIRONMENT_KAFKA_INITIAL_OFFSET}','ES_FILEBEAT_KAFKA_SSL=${INGEST_KAFKA_SASL_ENVIRONMENT_KAFKA_SSL}','ES_FILEBEAT_KAFKA_USERNAME=${INGEST_KAFKA_SASL_ENVIRONMENT_KAFKA_USERNAME}','ES_FILEBEAT_KAFKA_PASSWORD=${INGEST_KAFKA_SASL_ENVIRONMENT_KAFKA_PASSWORD}','ES_FILEBEAT_OUTPUT_CONSOLE=${INGEST_KAFKA_SASL_ENVIRONMENT_OUTPUT_CONSOLE}','ES_FILEBEAT_OUTPUT_ELASTICSEARCH=${INGEST_KAFKA_SASL_ENVIRONMENT_OUTPUT_ELASTICSEARCH}','ES_FILEBEAT_OUTPUT_LOGSTASH=${INGEST_KAFKA_SASL_ENVIRONMENT_OUTPUT_LOGSTASH}','ES_FILEBEAT_OUTPUT_KAFKA=${INGEST_KAFKA_SASL_ENVIRONMENT_OUTPUT_KAFKA}','ES_FILEBEAT_OUTPUT_CONFIG_ELASTICSEARCH_HOSTS=${INGEST_KAFKA_SASL_ENVIRONMENT_OUTPUT_CONFIG_ELASTICSEARCH_HOSTS}','ES_FILEBEAT_OUTPUT_CONFIG_ELASTICSEARCH_INDEX=${INGEST_KAFKA_SASL_ENVIRONMENT_OUTPUT_CONFIG_ELASTICSEARCH_INDEX}','ES_FILEBEAT_OUTPUT_CONFIG_LOGSTASH_HOSTS=${INGEST_KAFKA_SASL_ENVIRONMENT_OUTPUT_CONFIG_LOGSTASH_HOSTS}','ES_FILEBEAT_OUTPUT_CONFIG_LOGSTASH_INDEX=${INGEST_KAFKA_SASL_ENVIRONMENT_OUTPUT_CONFIG_LOGSTASH_INDEX}','ES_FILEBEAT_OUTPUT_CONFIG_KIBANA_HOST=${INGEST_KAFKA_SASL_ENVIRONMENT_OUTPUT_CONFIG_KIBANA_HOST}','ES_FILEBEAT_OUTPUT_CONFIG_KIBANA_DASHBOARDS=${INGEST_KAFKA_SASL_ENVIRONMENT_OUTPUT_CONFIG_KIBANA_DASHBOARDS}','ES_FILEBEAT_OUTPUT_CONFIG_KAFKA_HOSTS=${INGEST_KAFKA_SASL_ENVIRONMENT_OUTPUT_CONFIG_KAFKA_HOSTS}','ES_FILEBEAT_OUTPUT_CONFIG_KAFKA_TOPIC=${INGEST_KAFKA_SASL_ENVIRONMENT_OUTPUT_CONFIG_KAFKA_TOPIC}']
    command: []
    volumes: ['${CONTECO_STACKPREFIX}_filebeat_volume:/usr/share/filebeat/data']
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${INGEST_KAFKA_SASL_DEPLOY_MODE}
      resources:
        limits:
          memory: '${INGEST_KAFKA_SASL_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${INGEST_KAFKA_SASL_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${INGEST_KAFKA_SASL_COMPOSE_EXTENSIONS}
# END SERVICE filebeat.kafka

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${CONTECO_STACKPREFIX}_filebeat_volume: { external: true }}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
